In [1]:
import numpy as np
from scipy.spatial.transform import Rotation as R
from scipy.spatial.transform import Slerp
import matplotlib.pyplot as plt
from sympy import *


In [9]:
a = np.array([0])
b = np.array([(i+1) for i in range(3)])
c = np.concatenate((a,b), 0)
print(c)

[0 1 2 3]


In [13]:
d = np.linspace(1,2,10)
print(d)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [15]:
a = ['a', 'b', 'c']
b = enumerate(a)
for i, j in b:
    print([i,j])

[0, 'a']
[1, 'b']
[2, 'c']


In [19]:
int(5/1)

5

In [18]:
np.zeros(2)

array([0., 0.])

In [43]:
num_cable = 8
n = 4
D = np.array([10, 20, 30, 40])
x_cable_bottom = np.zeros([n, num_cable*2]) ## one row represents x coordinate of all cable for one column
loc = np.hstack((np.linspace(-num_cable, -1, num_cable), np.linspace(1, num_cable, num_cable)))  ## help to locate x coordinate
for i in range(n):
    x_cable_bottom[i, :] = D[i] + 0.1 * loc
x_cable_bottom = x_cable_bottom.reshape([-1, 1])
z_cable_bottom = 0
y_cable_bottom = 1
cable_bottom_right = np.hstack((x_cable_bottom, x_cable_bottom*0+y_cable_bottom, x_cable_bottom*0+z_cable_bottom))
cable_bottom_left = cable_bottom_right * np.array([[1,-1,1]])
cable_bottom = np.concatenate([cable_bottom_left, cable_bottom_right], 0)
print((cable_bottom))

[[ 9.2 -1.   0. ]
 [ 9.3 -1.   0. ]
 [ 9.4 -1.   0. ]
 [ 9.5 -1.   0. ]
 [ 9.6 -1.   0. ]
 [ 9.7 -1.   0. ]
 [ 9.8 -1.   0. ]
 [ 9.9 -1.   0. ]
 [10.1 -1.   0. ]
 [10.2 -1.   0. ]
 [10.3 -1.   0. ]
 [10.4 -1.   0. ]
 [10.5 -1.   0. ]
 [10.6 -1.   0. ]
 [10.7 -1.   0. ]
 [10.8 -1.   0. ]
 [19.2 -1.   0. ]
 [19.3 -1.   0. ]
 [19.4 -1.   0. ]
 [19.5 -1.   0. ]
 [19.6 -1.   0. ]
 [19.7 -1.   0. ]
 [19.8 -1.   0. ]
 [19.9 -1.   0. ]
 [20.1 -1.   0. ]
 [20.2 -1.   0. ]
 [20.3 -1.   0. ]
 [20.4 -1.   0. ]
 [20.5 -1.   0. ]
 [20.6 -1.   0. ]
 [20.7 -1.   0. ]
 [20.8 -1.   0. ]
 [29.2 -1.   0. ]
 [29.3 -1.   0. ]
 [29.4 -1.   0. ]
 [29.5 -1.   0. ]
 [29.6 -1.   0. ]
 [29.7 -1.   0. ]
 [29.8 -1.   0. ]
 [29.9 -1.   0. ]
 [30.1 -1.   0. ]
 [30.2 -1.   0. ]
 [30.3 -1.   0. ]
 [30.4 -1.   0. ]
 [30.5 -1.   0. ]
 [30.6 -1.   0. ]
 [30.7 -1.   0. ]
 [30.8 -1.   0. ]
 [39.2 -1.   0. ]
 [39.3 -1.   0. ]
 [39.4 -1.   0. ]
 [39.5 -1.   0. ]
 [39.6 -1.   0. ]
 [39.7 -1.   0. ]
 [39.8 -1.   0. ]
 [39.9 -1.

In [37]:
D = np.array([10, 20, 30, 40])
x_cable_top = np.ones([4, 10]) * D.reshape([4,1])
print(x_cable_top)

[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
 [30. 30. 30. 30. 30. 30. 30. 30. 30. 30.]
 [40. 40. 40. 40. 40. 40. 40. 40. 40. 40.]]


In [38]:
np.linspace(8,1,8)

array([8., 7., 6., 5., 4., 3., 2., 1.])

In [41]:
n = 4
num_cable = 8
z_cable_top = np.zeros([n, num_cable*2]) 
loc = np.hstack((np.linspace(num_cable, 1, num_cable), np.linspace(1, num_cable, num_cable)))
for i in range(n):
    z_cable_top[i, :] = 5 + 2 * loc
print(z_cable_top)

[[21. 19. 17. 15. 13. 11.  9.  7.  7.  9. 11. 13. 15. 17. 19. 21.]
 [21. 19. 17. 15. 13. 11.  9.  7.  7.  9. 11. 13. 15. 17. 19. 21.]
 [21. 19. 17. 15. 13. 11.  9.  7.  7.  9. 11. 13. 15. 17. 19. 21.]
 [21. 19. 17. 15. 13. 11.  9.  7.  7.  9. 11. 13. 15. 17. 19. 21.]]


In [51]:
a = np.array([
    [1,2,3],
    [3,4,5]
])

b = a.reshape([1,-1])
print(b+1)

[[2 3 4 4 5 6]]


SyntaxError: cannot assign to operator (<ipython-input-48-c378cab9f24e>, line 2)