In [1]:
import numpy as np
import scipy
from scipy.spatial.transform import Rotation as R
from scipy.spatial.transform import Slerp
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

In [3]:
class people:
    def _init_(self):
        self.name=None
        self.age=None

chj=people()
chj.name='chj'
chj.age=22
print(chj.name)

chj


In [7]:
a=np.array([
    [1,2,3],
    [3,4,5]
])
print(a.shape)
print(a[:,0:3])

(2, 3)
[[1 2 3]
 [3 4 5]]


In [8]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b=a[:,1]
print(b)
c=b.reshape((b.shape[0],1))
print(c)
c.shape





[2 5 8]
[[2]
 [5]
 [8]]


(3, 1)

In [15]:
a=np.array([1,2,3])
b=a+1
c=tuple(b)
d=np.mod(np.arange(5),4)
print(d)
print(b)
print(c)

[0 1 2 3 0]
[2 3 4]
(2, 3, 4)


In [7]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b=a[:,1]
print(b)

[2 5 8]
